version: '3.8'
services:
  fintech-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin 
      - MYSQL_DATABASE=fintechDb
      - MYSQL_USER=fintechuser
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    expose:
      - 3306
       
  main:
    build: .
    image: fintech
    restart: on-failure
    depends_on:
      - fintech-mysql
    ports:
      - 8080:8080
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - DATABASE_PORT=3306
